name: Deploy server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo on runner
        uses: actions/checkout@v3

#      - name: Test ssh command
#        run: |
#          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_SERVER }} 'touch trying-to-do-something.txt'

      - name: Git pull
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            cd ~/cap-git
            git pull
            
